# Generated by Django 3.0.1 on 2019-12-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='repo_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
