# Generated by Django 3.0.1 on 2019-12-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191223_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='repo',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
